on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'checkout branch'
        required: true
        default: 'main'
  release:
    types: [created]

name: Deploy

jobs:
  webPage:
    name: Deploy webPage frontend to GithubPage
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: sdcconw/NGNTunnelBroker
        ref: '${{ github.event.inputs.branch }}'
        ssh-key: '${{ secrets.NGNTB_DEPLOY_SSHKEY }}'
        path: code

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: code/packages/web-page/node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('code/packages/web-page/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: node modules install
      run: |
        cd code/packages/web-page
        npm install

    - name: Vue build
      run: |
        cd code/packages/web-page
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: code/packages/web-page/dist
        cname: tb-demo.ngn.icu

    - name: Discord Notify
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: NGNTunnelBroker-web-page
        description: https://tb-demo.ngn.icu/
        nofail: false
        nodetail: false
        username: GitHub Actions